quarkus.http.port=8702
mp.openapi.extensions.smallrye.info.title=Book API
mp.openapi.extensions.smallrye.info.version=1.0
mp.openapi.extensions.smallrye.info.description="Creates Books"
mp.openapi.extensions.smallrye.contact.name=@luongnm
mp.openapi.extensions.smallrye.contact.url=1.0

number.proxy/mp-rest/uri=http://localhost:8701